'use client';

import { motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, MoveRight } from 'lucide-react';
import Link from 'next/link';

export function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`eyebrow ${light ? 'text-white/45' : 'text-black/40'}`}>{children}</p>; }
export function SectionHeading({ children, className = '', light = false }: { children: React.ReactNode; className?: string; light?: boolean }) { return <h2 className={`display-heading ${light ? 'text-white' : 'text-[#151617]'} ${className}`}>{children}</h2>; }
export function Button({ href, children, secondary = false, light = false }: { href: string; children: React.ReactNode; secondary?: boolean; light?: boolean }) { return <Link href={href} className={`group inline-flex min-h-12 items-center justify-center gap-3 rounded-full px-5 py-3 text-[10px] font-bold uppercase tracking-[.13em] transition-all hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#A3FF3F] focus-visible:ring-offset-2 ${secondary ? (light ? 'border border-white/20 text-white hover:bg-white/10' : 'border border-black/15 text-[#151617] hover:bg-black/[.03]') : (light ? 'bg-[#A3FF3F] text-[#151617] hover:bg-[#b8ff65]' : 'bg-[#151617] text-white hover:bg-[#232526]')}`}>{children}<ArrowUpRight size={14} className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link>; }

const systemData = [
  { number: '01', title: 'Growth Strategy', slug: 'growth-strategy', desc: 'Define where to play, how to win and what needs to change to unlock growth.', items: ['Go-to-market strategy', 'Positioning', 'Commercial validation', 'Growth strategy', 'Fractional growth leadership'] },
  { number: '02', title: 'Intelligent Growth Systems', slug: 'intelligent-growth-systems', desc: 'Turn repetitive work, slow response times and disconnected workflows into intelligent operating systems.', items: ['AI Voice Agents', 'WhatsApp automation', 'CRM workflows', 'Lead response', 'Customer operations'] },
  { number: '03', title: 'Digital Experience & Conversion', slug: 'digital-experience', desc: 'Build digital experiences that turn attention into action and action into revenue.', items: ['Websites', 'Shopify', 'UX/UI', 'Conversion optimization', 'Customer journeys'] },
  { number: '04', title: 'Demand & Content', slug: 'demand-content', desc: 'Create and amplify demand through content and campaigns built around measurable commercial outcomes.', items: ['Performance marketing', 'Social', 'AI-powered content', 'Video', 'Demand generation'] },
];

export function SystemsSection() { return <section id="systems" className="section-pad border-t border-black/10 bg-[#FAFAF8]"><div className="container"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><div><Eyebrow>Where we engineer growth</Eyebrow><SectionHeading className="mt-5 max-w-md">One growth partner.<br /><span className="muted">Four connected systems.</span></SectionHeading><p className="body-copy mt-6 max-w-md">Growth rarely lives inside one department. We connect the strategic, operational, digital and demand systems that determine commercial performance.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-black/10 bg-black/10 sm:grid-cols-2">{systemData.map((system, i) => <motion.article key={system.number} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .5, delay: i * .05 }} className="group bg-white p-6 sm:p-7 lg:p-8"><div className="flex items-center justify-between"><span className="number">{system.number}</span><Link href={`/solutions/${system.slug}`} className="grid h-9 w-9 place-items-center rounded-full border border-black/10 transition-colors group-hover:border-[#A3FF3F] group-hover:bg-[#A3FF3F]" aria-label={`Explore ${system.title}`}><ArrowUpRight size={14} /></Link></div><h3 className="mt-14 font-[family-name:var(--font-manrope)] text-xl font-bold tracking-[-.025em] lg:text-2xl">{system.title}</h3><p className="mt-3 text-sm leading-6 text-black/50">{system.desc}</p><div className="mt-6 flex flex-wrap gap-2">{system.items.map(item => <span key={item} className="rounded-full border border-black/10 px-2.5 py-1.5 text-[9px] font-medium uppercase tracking-[.08em] text-black/45">{item}</span>)}</div></motion.article>)}</div></div></div></section>; }

export function MomentumSection() { return <section className="section-pad bg-white"><div className="container"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:items-end"><div><Eyebrow>The growth gap</Eyebrow><SectionHeading className="mt-5">Your business isn&apos;t lacking tools.<br /><span className="muted">It may be lacking connection.</span></SectionHeading><p className="body-copy mt-6 max-w-md">Most growing businesses accumulate strategy, marketing, sales, technology, AI, customer experience and operations. The constraint appears when those systems operate independently.</p><Button href="#equation" secondary>See the bigger picture</Button></div><SystemGraphic /></div></div></section>; }
function SystemGraphic() { const reduce = useReducedMotion(); const labels = ['Strategy', 'Marketing', 'Technology', 'AI', 'Operations', 'Customer Experience']; return <div className="relative min-h-[390px] overflow-hidden rounded-2xl border border-black/10 bg-[#F0F1F1] p-5 sm:p-8"><div className="absolute inset-0 grid-bg opacity-70" /><svg viewBox="0 0 640 390" className="absolute inset-0 h-full w-full" aria-hidden="true"><g fill="none" stroke="rgba(21,22,23,.16)" strokeWidth="1"><path d="M120 75 C230 55 270 170 320 195 C370 220 400 90 510 85"/><path d="M105 300 C230 330 250 215 320 195 C390 175 430 295 525 285"/><path d="M125 75 C155 150 160 245 105 300"/><path d="M510 85 C500 160 490 230 525 285"/></g></svg><div className="relative grid h-full grid-cols-2 grid-rows-3 gap-4 sm:grid-cols-3">{labels.map((item, i) => <motion.div key={item} initial={reduce ? undefined : { opacity: 0, scale: .96 }} whileInView={reduce ? undefined : { opacity: 1, scale: 1 }} viewport={{ once: true }} transition={reduce ? undefined : { delay: i * .06 }} className="flex items-center justify-center rounded-xl border border-black/10 bg-white/90 p-4 text-center shadow-sm"><span className="text-xs font-semibold">{item}</span></motion.div>)}</div><div className="absolute bottom-5 left-1/2 grid h-12 w-12 -translate-x-1/2 place-items-center rounded-full bg-[#151617] text-[#A3FF3F] shadow-xl"><span className="h-2 w-2 rounded-full bg-[#A3FF3F]" /></div></div>; }

const flow = ['Strategy', 'Demand', 'Conversion', 'Intelligent Systems', 'Customer Experience', 'Revenue', 'Scale'];
export function FlowSection() { return <section className="section-pad bg-[#FAFAF8]"><div className="container"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Eyebrow>The Nexoreya approach</Eyebrow><SectionHeading className="mt-5 max-w-2xl">From complexity to clarity.<br />From clarity to momentum.</SectionHeading></div><p className="body-copy max-w-sm">When everything works together, growth compounds.</p></div><div className="mt-14 overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="grid divide-y divide-black/10 md:grid-cols-7 md:divide-x md:divide-y-0">{flow.map((item, i) => <motion.div key={item} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .06 }} className="relative flex min-h-32 items-center gap-4 p-5 md:block md:min-h-52 md:p-5"><span className="text-[9px] font-bold tracking-[.18em] text-black/30">0{i + 1}</span><div className="mt-0 md:mt-12"><p className="font-[family-name:var(--font-manrope)] text-sm font-bold leading-tight">{item}</p><span className="mt-3 block h-px w-7 bg-[#A3FF3F]" /></div>{i < flow.length - 1 && <MoveRight className="absolute right-4 top-1/2 hidden text-black/20 md:block" size={14} />}</motion.div>)}</div></div></div></section>; }

export function MethodSection() { const steps = [['01', 'Diagnose', 'Understand the business, constraints, opportunities and economics before recommending technology.'], ['02', 'Design', 'Design the system around measurable outcomes, leverage and the highest-value opportunities.'], ['03', 'Build', 'Build, integrate and deploy the systems required to create the desired business outcome.'], ['04', 'Measure', 'Track the signals that matter and determine whether the system is producing results.'], ['05', 'Optimize', 'Continuously improve performance based on real-world data.'], ['06', 'Scale', 'Expand what works across channels, teams, locations and markets.']]; return <section className="section-pad bg-[#151617] text-white"><div className="container"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Eyebrow light>The Nexoreya difference</Eyebrow><SectionHeading light className="mt-5 max-w-xl">We don&apos;t start with technology.<br /><span className="text-white/35">We start with the business.</span></SectionHeading><p className="mt-6 max-w-md text-sm leading-7 text-white/50">Diagnosis comes before prescription. We identify the constraint, design the right system, build deliberately, then measure and improve what matters.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([n, t, c]) => <motion.div key={n} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} className="bg-[#151617] p-6"><span className="text-[10px] font-bold text-[#A3FF3F]">{n}</span><h3 className="mt-10 font-[family-name:var(--font-manrope)] text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-white/40">{c}</p></motion.div>)}</div></div></div></section>; }

const metrics = [['$18M', 'Channel portfolio'], ['$100K/mo', 'Revenue growth'], ['4.83×', 'Amazon PPC ROAS'], ['15×', 'Meta ROAS'], ['22%', 'YoY QSR growth']];
export function ProofSection() { return <section className="section-pad bg-white"><div className="container"><Eyebrow>Commercial experience</Eyebrow><div className="mt-5 flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading>Built on experience.<br /><span className="muted">Measured by outcomes.</span></SectionHeading><p className="max-w-sm text-xs leading-5 text-black/45">Selected commercial experience and outcomes from work across growth, e-commerce, performance marketing and customer operations.</p></div><div className="mt-12 grid border-y border-black/10 sm:grid-cols-2 lg:grid-cols-5">{metrics.map(([value, label]) => <div key={label} className="border-b border-black/10 p-6 lg:border-b-0 lg:border-r lg:last:border-r-0"><p className="font-[family-name:var(--font-manrope)] text-3xl font-extrabold tracking-[-.05em] lg:text-4xl">{value}</p><p className="mt-3 text-[9px] font-semibold uppercase tracking-[.14em] text-black/40">{label}</p></div>)}</div></div></section>; }

const cases = [['AI / Customer Experience', 'Turning missed calls into captured opportunities.', 'ai-voice-agent'], ['E-commerce / Growth', 'From traffic to profitable conversion.', 'ecommerce-growth'], ['QSR / Performance', 'Building growth across nine locations.', 'qsr-performance']];
export function CaseStudiesSection() { return <section id="case-studies" className="section-pad bg-[#FAFAF8]"><div className="container"><div className="flex items-end justify-between gap-6"><div><Eyebrow>Case studies</Eyebrow><SectionHeading className="mt-5">Proof is better than promises.</SectionHeading></div><Button href="#contact" secondary>View all case studies</Button></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{cases.map(([tag, title, slug], i) => <Link key={slug} href={`/case-studies/${slug}`} className="group overflow-hidden rounded-2xl border border-black/10 bg-white"><div className={`relative aspect-[1.2] overflow-hidden ${i === 0 ? 'bg-[#151617]' : 'bg-[#E7EAE8]'}`}><div className="absolute inset-0 grid-bg opacity-50" /><div className="absolute bottom-6 left-6 right-6"><span className={`text-[9px] font-bold uppercase tracking-[.18em] ${i === 0 ? 'text-[#A3FF3F]' : 'text-black/40'}`}>{tag}</span><h3 className={`mt-3 max-w-xs font-[family-name:var(--font-manrope)] text-2xl font-bold leading-tight tracking-[-.035em] ${i === 0 ? 'text-white' : 'text-[#151617]'}`}>{title}</h3></div></div><div className="flex items-center justify-between p-5"><span className="text-xs font-semibold">Read Case Study</span><ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div></Link>)}</div></div></section>; }

export function EquationSection() { return <section id="equation" className="section-pad border-y border-black/10 bg-white"><div className="container"><Eyebrow>How we think</Eyebrow><SectionHeading className="mt-5 max-w-3xl">Growth = Strategy × Systems × Execution</SectionHeading><div className="mt-12 grid gap-0 overflow-hidden rounded-2xl border border-black/10 md:grid-cols-3"><div className="p-7 md:p-10"><span className="number">01</span><h3 className="mt-12 text-xl font-bold">Strategy</h3><p className="body-copy mt-3">Where are you going?</p></div><div className="border-y border-black/10 bg-[#151617] p-7 text-white md:border-x md:border-y-0 md:p-10"><span className="text-[9px] font-bold uppercase tracking-[.18em] text-[#A3FF3F]">Measurable growth</span><h3 className="mt-12 font-[family-name:var(--font-manrope)] text-3xl font-extrabold tracking-[-.04em]">Connected.</h3><p className="mt-3 text-sm leading-6 text-white/45">The three reinforce one another.</p></div><div className="p-7 md:p-10"><span className="number">03</span><h3 className="mt-12 text-xl font-bold">Execution</h3><p className="body-copy mt-3">How do we make it happen?</p></div></div><p className="mt-8 max-w-2xl text-sm leading-7 text-black/50">Strategy without systems stays theoretical. Systems without execution stay unused. Execution without strategy creates activity without direction.</p></div></section>; }

export function FounderSection() { return <section className="section-pad bg-white"><div className="container"><div className="grid overflow-hidden rounded-2xl border border-black/10 lg:grid-cols-[.9fr_1.1fr]"><div className="min-h-[420px] bg-[#E8EBE8] p-8 lg:p-10"><div className="flex h-full items-end"><div><Eyebrow>Founder</Eyebrow><p className="mt-4 font-[family-name:var(--font-manrope)] text-4xl font-extrabold tracking-[-.05em]">Fahad Khalil</p><p className="mt-2 text-xs font-semibold uppercase tracking-[.12em] text-black/40">Founder, Nexoreya</p></div></div></div><div className="flex flex-col justify-between bg-[#151617] p-8 text-white lg:p-12"><div><Eyebrow light>Built by a commercial operator.</Eyebrow><SectionHeading light className="mt-5">20+ years of commercial experience.</SectionHeading><p className="mt-7 max-w-lg text-sm leading-7 text-white/50">Growth, e-commerce, performance marketing, customer operations, digital transformation and business development — brought together around one question: what will actually move the business?</p></div><Link href="/about" className="mt-10 inline-flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.14em] text-[#A3FF3F]">Meet Fahad <ArrowUpRight size={14} /></Link></div></div></div></section>; }

export function ProcessSection() { const items = [['01','Discover','Understand the business.'],['02','Diagnose','Identify constraints and opportunities.'],['03','Design','Architect the right solution.'],['04','Build','Implement the system.'],['05','Optimize','Measure, improve and scale.']]; return <section id="process" className="section-pad bg-[#FAFAF8]"><div className="container"><Eyebrow>How we work</Eyebrow><SectionHeading className="mt-5">Think first. Build deliberately. Improve continuously.</SectionHeading><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-black/10 bg-black/10 md:grid-cols-5">{items.map(([n,t,c])=><div key={n} className="bg-white p-6"><span className="text-[10px] font-bold text-[#7ebd16]">{n}</span><h3 className="mt-12 font-[family-name:var(--font-manrope)] text-lg font-bold">{t}</h3><p className="mt-3 text-xs leading-5 text-black/45">{c}</p></div>)}</div></div></section>; }

export function IntelligenceSection() { const items=[['GROWTH','AI isn’t the strategy. It’s the leverage.'],['INTELLIGENT SYSTEMS','Your lead-generation problem might actually be a response-time problem.'],['TRANSFORMATION','Digital transformation fails when technology moves faster than the business.']]; return <section id="intelligence" className="section-pad bg-white"><div className="container"><div className="flex items-end justify-between gap-6"><div><Eyebrow>Nexoreya intelligence</Eyebrow><SectionHeading className="mt-5">Ideas worth paying attention to.</SectionHeading></div><Button href="#contact" secondary>Explore all insights</Button></div><div className="mt-12 grid gap-5 md:grid-cols-3">{items.map(([tag,title],i)=><Link href={`/intelligence/${i+1}`} key={tag} className="group overflow-hidden rounded-2xl border border-black/10"><div className="relative aspect-[1.55] bg-[#F0F1F1]"><div className="absolute inset-0 grid-bg" /><div className="absolute bottom-5 left-5 h-12 w-12 rounded-full border border-black/10 bg-white/70" /></div><div className="p-6"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[#7ebd16]">{tag}</p><h3 className="mt-4 font-[family-name:var(--font-manrope)] text-xl font-bold leading-tight tracking-[-.025em]">{title}</h3><span className="mt-8 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.12em]">Read article <ArrowUpRight size={13} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></div></Link>)}</div></div></section>; }

export function FinalCTA() { return <section id="contact" className="relative overflow-hidden bg-[#F0F1F1] py-28 sm:py-36"><div className="absolute inset-0 grid-bg opacity-50" /><div className="relative container"><div className="grid gap-12 lg:grid-cols-[1fr_auto] lg:items-end"><div><Eyebrow>Let&apos;s build what&apos;s next</Eyebrow><SectionHeading className="mt-5 max-w-3xl">Ready to build what&apos;s next?</SectionHeading><p className="body-copy mt-6 max-w-xl">Let&apos;s identify where growth is being constrained — and engineer the system to unlock it.</p></div><Button href="/contact">Book a Growth Strategy Session</Button></div><div className="mt-12 flex items-center gap-4 text-[9px] font-semibold uppercase tracking-[.2em] text-black/35"><span className="h-2 w-2 rounded-full bg-[#A3FF3F]" /> A more intelligent tomorrow.</div></div></section>; }
